import { Property, Client } from '../types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: '中信红树湾 3室2厅 前山河景 奢华精装 钥匙在店 随时看房',
    community: '中信红树湾',
    district: '香洲区 / 南湾',
    type: 'sale',
    price: 480,
    unitPrice: 34782,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 2,
    area: 138,
    floor: 'high',
    totalFloors: 32,
    hasElevator: true,
    orientation: '南北通透',
    decoration: 'luxury',
    tags: ['一线河景', '带电梯', '南北通透', '成熟大盘', '管家物业', '双阳台', '随时看房'],
    highlights: '珠海前山河畔豪宅标杆，高楼层视野开阔俯瞰河景，近华发商都，全屋进口品牌中央空调与地暖，业主诚意急售置换横琴。',
    address: '香洲区前河西路333号',
    subwayDistance: '距城轨前山站驾车5分钟，距拱北口岸10分钟',
    ownerName: '陈总',
    ownerPhone: '139-2241-8899',
    minPrice: 465,
    status: 'active',
    notes: '钥匙已留门店，看房提前半小时联系即可。满五唯一，税费成本极低。',
    createdAt: '2026-09-20 10:30',
    updatedAt: '2026-09-28 15:20',
  },
  {
    id: 'prop-002',
    title: '仁恒滨海半岛 3室2厅 一线海景 深中通道落脚点 次新精装拎包住',
    community: '仁恒滨海半岛',
    district: '高新区 / 唐家湾',
    type: 'sale',
    price: 265,
    unitPrice: 27604,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 2,
    area: 96,
    floor: 'middle',
    totalFloors: 30,
    hasElevator: true,
    orientation: '纯南向',
    decoration: 'refined',
    tags: ['一线海景', '带电梯', '纯南向', '次新小区', '仁恒物业', '深中通道首站'],
    highlights: '唐家半岛品质名盘，下楼即是情侣北路滨海绿道，正南向超阔阳台无遮挡望海；近珠海北站及深中通道出口。',
    address: '高新区唐家湾情侣北路',
    subwayDistance: '近城轨珠海北站与唐家湾站，距深中通道连接线约8分钟',
    ownerName: '林小姐',
    ownerPhone: '137-5590-1234',
    minPrice: 255,
    status: 'active',
    notes: '仁恒自住标准精装，保养极佳。房东因调去深圳工作诚意出售。',
    createdAt: '2026-09-22 14:10',
    updatedAt: '2026-09-29 09:40',
  },
  {
    id: 'prop-003',
    title: '岭南世家 3室2厅 文园中学+香洲一小优质双学区 加装电梯诚售',
    community: '岭南世家',
    district: '香洲区 / 新香洲',
    type: 'sale',
    price: 320,
    unitPrice: 35955,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 1,
    area: 89,
    floor: 'middle',
    totalFloors: 9,
    hasElevator: true,
    orientation: '南北通透',
    decoration: 'refined',
    tags: ['优质学区', '文园双学位', '带电梯', '成熟商圈', '满五唯一', '采光好'],
    highlights: '对口珠海公办顶流文园中学+香洲一小，学位完全空出未占用；新香洲行政核心，周边体育中心、妇女儿童活动中心配套极完善。',
    address: '香洲区迎宾北路1066号',
    subwayDistance: '周边多条快线公交直达吉大与拱北',
    ownerName: '何老师',
    ownerPhone: '136-0982-4433',
    minPrice: 310,
    status: 'active',
    notes: '孩子已保送外地大学，学位完全空出。加装电梯分摊款已结清。',
    createdAt: '2026-09-18 11:00',
    updatedAt: '2026-09-27 16:00',
  },
  {
    id: 'prop-004',
    title: '华发新城五期 2室2厅 正南朝向 邻近南湾华发商都 拱北通勤首选',
    community: '华发新城',
    district: '香洲区 / 南湾',
    type: 'sale',
    price: 188,
    unitPrice: 24102,
    rooms: 2,
    livingRooms: 2,
    bathrooms: 1,
    area: 78,
    floor: 'middle',
    totalFloors: 26,
    hasElevator: true,
    orientation: '朝南',
    decoration: 'refined',
    tags: ['成熟大盘', '带电梯', '朝南', '精装拎包住', '华发物业', '低总价'],
    highlights: '珠海公认经典居住大盘，园林绿化覆盖率高；紧邻华发商都生活圈，10分钟车程直通拱北口岸与横琴大桥。',
    address: '香洲区珠海大道1号',
    subwayDistance: '出门即华发新城公交总站，多条专线直通口岸',
    ownerName: '周先生',
    ownerPhone: '135-6019-3321',
    minPrice: 182,
    status: 'active',
    notes: '全屋品牌家私家电赠送，客厅出南向大阳台，随时可看。',
    createdAt: '2026-09-25 15:30',
    updatedAt: '2026-09-29 11:20',
  },
  {
    id: 'prop-005',
    title: '横琴华发首府 3室2厅 琴澳一体化核心区 口岸专线 单牌车便利',
    community: '华发首府',
    district: '横琴合作区 / 金融岛',
    type: 'sale',
    price: 435,
    unitPrice: 41428,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 2,
    area: 105,
    floor: 'high',
    totalFloors: 32,
    hasElevator: true,
    orientation: '纯南向',
    decoration: 'luxury',
    tags: ['横琴核心', '带电梯', '纯南向', '双阳台', '双卫', '澳门生活圈'],
    highlights: '横琴自贸区与金融岛交汇核心，临近天沐河生态公园，澳门单牌车自由出入，享深合区分线管理多项税收政策红利。',
    address: '横琴合作区琴飞道与濠江路交汇处',
    subwayDistance: '车程5分钟直达横琴口岸通关澳门',
    ownerName: '徐董',
    ownerPhone: '139-0223-9000',
    minPrice: 420,
    status: 'active',
    notes: '业主常住澳门，诚意出售，看房提前一天预约密码锁。',
    createdAt: '2026-09-10 16:00',
    updatedAt: '2026-09-28 18:00',
  },
  {
    id: 'prop-006',
    title: '时代山湖海 3室2厅 金湾航空新城核心 华发商都商圈 高性价比',
    community: '时代山湖海',
    district: '金湾区 / 航空新城',
    type: 'sale',
    price: 135,
    unitPrice: 15340,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 1,
    area: 88,
    floor: 'middle',
    totalFloors: 24,
    hasElevator: true,
    orientation: '南北通透',
    decoration: 'refined',
    tags: ['航空新城', '带电梯', '低总价3房', '金湾华发商都', '采光好', '近机场高速'],
    highlights: '航空新城核芯成熟社区，周边市民艺术中心、金山公园环绕，洪鹤大桥通车后到香洲仅需20分钟。',
    address: '金湾区三灶镇金岛路108号',
    subwayDistance: '金湾互通立交旁，高速通达香洲与横琴',
    ownerName: '梁伯',
    ownerPhone: '133-8899-0011',
    minPrice: 128,
    status: 'active',
    notes: '业主退休去广州与子女同住，急售变现，价格有商量空间。',
    createdAt: '2026-09-23 11:45',
    updatedAt: '2026-09-29 16:50',
  },
  {
    id: 'prop-007',
    title: '华发世纪城 1室1厅 拱北关口涉外高档社区 步行口岸 精装整租',
    community: '华发世纪城',
    district: '香洲区 / 拱北',
    type: 'rent',
    price: 3200,
    rooms: 1,
    livingRooms: 1,
    bathrooms: 1,
    area: 45,
    floor: 'middle',
    totalFloors: 28,
    hasElevator: true,
    orientation: '朝东',
    decoration: 'refined',
    tags: ['步行口岸', '涉外社区', '精装拎包住', '独立厨卫', '带电梯', '民水民电'],
    highlights: '前山河出海口一线水景，出门即是世纪城商业街；步行或单车10分钟即可通关澳门拱北口岸/青茂口岸。',
    address: '香洲区侨光路666号',
    subwayDistance: '距城轨珠海站与拱北口岸步行约1.2公里',
    ownerName: '王姐',
    ownerPhone: '133-1122-3344',
    minPrice: 3000,
    status: 'active',
    notes: '澳门上班白领首选，支持押一付一，要求生活规律，室内禁烟。',
    createdAt: '2026-09-24 17:00',
    updatedAt: '2026-09-29 19:30',
  },
  {
    id: 'prop-008',
    title: '港湾1号青年公寓 1室0厅 Loft复式 紧邻金山软件/高新智谷 精装出租',
    community: '港湾1号科创公馆',
    district: '高新区 / 唐家湾',
    type: 'rent',
    price: 2200,
    rooms: 1,
    livingRooms: 1,
    bathrooms: 1,
    area: 36,
    floor: 'middle',
    totalFloors: 16,
    hasElevator: true,
    orientation: '朝南',
    decoration: 'refined',
    tags: ['Loft复式', '近金山软件', '高新区科创', '带电梯', '青年社区', '随时看房'],
    highlights: '唐家湾科创基地核心，步行5分钟至金山软件大厦、远光软件总部；楼下为港湾1号文创园区，生活便利。',
    address: '高新区唐家湾港湾1号科创园',
    subwayDistance: '近城轨唐家湾站，深中通道通勤圈',
    ownerName: '刘女士',
    ownerPhone: '136-7788-9900',
    minPrice: 2100,
    status: 'active',
    notes: '配备全套智能家电、指纹门锁，免物业费，长租可优惠。',
    createdAt: '2026-09-21 16:30',
    updatedAt: '2026-09-28 10:20',
  },
  {
    id: 'prop-009',
    title: '九洲绿城翠湖香山 4室2厅 纯正高尔夫全景大平层 奢华大宅',
    community: '翠湖香山',
    district: '高新区 / 唐家湾',
    type: 'sale',
    price: 780,
    unitPrice: 40000,
    rooms: 4,
    livingRooms: 2,
    bathrooms: 3,
    area: 195,
    floor: 'high',
    totalFloors: 18,
    hasElevator: true,
    orientation: '纯南向',
    decoration: 'luxury',
    tags: ['高尔夫景观', '顶豪圈层', '双阳台', '私人电梯入户', '带车位', '带电梯'],
    highlights: '坐落于国际标准翠湖高尔夫球场中央，纯正南向270度果岭全景视野，绿城高端法式匠筑，独立保姆间设计。',
    address: '高新区唐家湾凯旋路翠湖香山',
    subwayDistance: '距城轨唐家湾站驾车3分钟，深中通道快速连通',
    ownerName: '郭先生',
    ownerPhone: '138-2345-6789',
    minPrice: 750,
    status: 'active',
    notes: '看房提前一天预约安排物业管家开门，赠送地下双产权车位。',
    createdAt: '2026-09-26 12:00',
    updatedAt: '2026-09-29 14:10',
  },
  {
    id: 'prop-010',
    title: '家和城 3室2厅 斗门湖心新城大盘 自带大型商业街 刚需首选',
    community: '家和城',
    district: '斗门区 / 湖心路',
    type: 'sale',
    price: 112,
    unitPrice: 11428,
    rooms: 3,
    livingRooms: 2,
    bathrooms: 1,
    area: 98,
    floor: 'middle',
    totalFloors: 30,
    hasElevator: true,
    orientation: '南北通透',
    decoration: 'refined',
    tags: ['低总价3房', '带电梯', '成熟商圈', '自带商场', '满五唯一', '首付低'],
    highlights: '斗门湖心路标杆综合体，楼下就是家和城一站式购物广场，对口齐正小学；首付20万内即可安家珠海。',
    address: '斗门区湖心路1098号',
    subwayDistance: '湖心路交通主干道，香海大桥快速接驳香洲南屏',
    ownerName: '黄阿姨',
    ownerPhone: '138-0012-9988',
    minPrice: 108,
    status: 'active',
    notes: '租约刚到期，空房钥匙在手随时可看，诚意买家价格可面谈。',
    createdAt: '2026-09-15 09:00',
    updatedAt: '2026-09-26 14:00',
  }
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-001',
    name: '张先生 & 李女士',
    phone: '138-0013-8822',
    wechat: 'zhang_zhuhai_tech',
    clientType: 'first_home',
    targetType: 'sale',
    minBudget: 220,
    maxBudget: 280,
    preferredDistricts: ['高新区', '香洲区'],
    preferredRooms: [3],
    minArea: 85,
    keyRequirements: ['近深中通道', '带电梯', '纯南向', '次新小区'],
    urgency: 'urgent',
    familyNotes: '夫妻都在高新区唐家湾高新科技园做研发，准备备孕买首套房，特别看重近唐家湾/深中通道通勤，要求电梯3房带南向阳台。',
    stage: 'viewing',
    notes: '已实地约看仁恒滨海半岛，对小区海景和仁恒物业非常满意，本周末准备复看谈价。',
    createdAt: '2026-09-25 09:30',
    updatedAt: '2026-09-29 10:15',
  },
  {
    id: 'client-002',
    name: '王总 (澳门投资人)',
    phone: '139-2233-4455',
    wechat: 'wang_macau_invest',
    clientType: 'upgrade',
    targetType: 'sale',
    minBudget: 600,
    maxBudget: 900,
    preferredDistricts: ['横琴合作区', '高新区', '香洲区'],
    preferredRooms: [4],
    minArea: 160,
    keyRequirements: ['带电梯', '南北通透', '高尔夫景观', '一线海景', '管家物业'],
    urgency: 'medium',
    familyNotes: '在澳门与珠海两地经商，拥有澳门单牌车，想在横琴或高新区购置一套一线景观大平层做家庭度假与资产配置，必须私密圈层好。',
    stage: 'matched',
    notes: '预算充裕可全款，重点对比了翠湖香山高尔夫大平层与横琴华发首府，等待回珠海复看。',
    createdAt: '2026-09-23 15:00',
    updatedAt: '2026-09-28 17:40',
  },
  {
    id: 'client-003',
    name: '赵老师 (家长群代表)',
    phone: '136-1234-5678',
    wechat: 'zhao_teacher_wenyuan',
    clientType: 'upgrade',
    targetType: 'sale',
    minBudget: 300,
    maxBudget: 360,
    preferredDistricts: ['香洲区'],
    preferredRooms: [3],
    minArea: 80,
    keyRequirements: ['优质学区', '文园双学位', '带电梯', '成熟商圈'],
    urgency: 'urgent',
    familyNotes: '小孩后年读文园中学，指定新香洲对口片区，学位必须未占用；家里有老人帮带孩子，要求必须带电梯。',
    stage: 'negotiating',
    notes: '正看中岭南世家3房，正与业主何老师协商把总价压到315万内。',
    createdAt: '2026-09-20 14:20',
    updatedAt: '2026-09-29 18:20',
  },
  {
    id: 'client-004',
    name: '陈小姐 (澳门通勤白领)',
    phone: '135-9988-7766',
    wechat: 'chen_macau_office',
    clientType: 'tenant',
    targetType: 'rent',
    minBudget: 2800,
    maxBudget: 3500,
    preferredDistricts: ['香洲区'],
    preferredRooms: [1],
    minArea: 40,
    keyRequirements: ['步行口岸', '涉外社区', '精装拎包住', '独立厨卫', '带电梯'],
    urgency: 'urgent',
    familyNotes: '每天从拱北口岸过关至澳门氹仔上班，要求离拱北口岸步行或单车10分钟以内，独居注重安保，必须有民水民电和大阳台。',
    stage: 'matched',
    notes: '原租约月底到期，已向其推荐华发世纪城1室1厅（3200元），周四晚上带看。',
    createdAt: '2026-09-28 10:00',
    updatedAt: '2026-09-29 11:30',
  },
  {
    id: 'client-005',
    name: '林阿姨 & 孙叔叔',
    phone: '133-4455-6677',
    wechat: 'lin_elderly_zhuhai',
    clientType: 'upgrade',
    targetType: 'sale',
    minBudget: 170,
    maxBudget: 210,
    preferredDistricts: ['香洲区'],
    preferredRooms: [2, 3],
    minArea: 75,
    keyRequirements: ['带电梯', '成熟大盘', '华发物业', '低总价', '朝南'],
    urgency: 'medium',
    familyNotes: '住在香洲柠溪老楼梯房7楼，老人膝盖关节不好下不来楼，想在南湾或前山换一套带电梯的华发大盘，孙子周末来住。',
    stage: 'viewing',
    notes: '对华发新城188万南向2房非常动心，已带全家老小看过一次，准备复盘首付款。',
    createdAt: '2026-09-24 16:40',
    updatedAt: '2026-09-27 15:10',
  },
  {
    id: 'client-006',
    name: '郭工程师 (智能科技研发)',
    phone: '137-8899-1122',
    wechat: 'guo_zhuhai_tech',
    clientType: 'tenant',
    targetType: 'rent',
    minBudget: 1800,
    maxBudget: 2400,
    preferredDistricts: ['高新区'],
    preferredRooms: [1],
    minArea: 30,
    keyRequirements: ['Loft复式', '近金山软件', '高新区科创', '带电梯'],
    urgency: 'urgent',
    familyNotes: '刚从深圳调派到珠海唐家湾金山软件园，希望离公司近，步行上下班，喜欢干净简洁的Loft公寓。',
    stage: 'closed',
    notes: '已顺利签约港湾1号公馆Loft复式，月租2200元，租期一年，已入住。',
    createdAt: '2026-09-29 08:30',
    updatedAt: '2026-09-29 09:15',
  }
];

export const COMMON_TAGS = [
  '近口岸',
  '带电梯',
  '优质学区',
  '文园双学位',
  '南北通透',
  '纯南向',
  '一线海景',
  '一线河景',
  '精装拎包住',
  '满五唯一',
  '深中通道首站',
  '高尔夫景观',
  '随时看房',
  '双阳台',
  '低总价',
  '成熟大盘',
  '横琴核心',
  '航空新城',
  '华发物业',
  '独立厨卫'
];

export const DISTRICT_OPTIONS = [
  '香洲区',
  '横琴合作区',
  '高新区',
  '金湾区',
  '斗门区',
  '保税区'
];
